title:
  archive: Archive
  category: Category
  tag: Tag
  schedule: Schedule

author: Author

menu:
  home: 首页
  archives: 归档
  categories: 分类
  tags: 标签
  about: 关于
  search: 搜索
  photos: 相册
  schedule: 日程
  sitemap: 网站地图
  commonweal: 公益404

sidebar:
  overview: 站点概览
  toc: 文章目录

post:
  created: Post created
  modified: Post modified
  sticky: Sticky
  posted: Posted on
  in: In
  more: more
  read_more: Read more
  untitled: Untitled
  toc_empty: This post does not have a Table of Contents
  visitors: Visitors
  wordcount: Words count in article
  min2read: Reading time
  totalcount: Site words total count
  copyright:
    author: Post author
    link: Post link
    license_title: Copyright Notice
    license_content: 'All articles in this blog are licensed under
      <a href="%s" rel="external nofollow" target="_blank">%s</a> unless stating additionally.'

page:
  totally: Totally
  tags: tags

footer:
  powered: "Powered by %s"
  theme: Theme

counter:
  tag_cloud:
    zero: No tags
    one: 1 tag in total
    other: "%d tags in total"

  categories:
    zero: No categories
    one: 1 category in total
    other: "%d categories in total"

  archive_posts:
    zero: No posts.
    one: 1 post.
    other: "%d posts in total."

state:
  posts: 发布
  pages: 页面
  tags: 标签
  categories: 分类

search:
  placeholder: Searching...

cheers:
  um: Um..
  ok: OK
  nice: Nice
  good: Good
  great: Great
  excellent: Excellent

keep_on: Keep on posting.

symbol:
  comma: ', '
  period: '. '
  colon: ':'

reward:
  donate: Donate
  wechatpay: WeChat Pay
  alipay: Alipay
  bitcoin: Bitcoin
