# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches:
      - src/hexo

env:
  TZ: Asia/Shanghai

jobs:
  update-blog:
    name: update hexo blog
    runs-on: ubuntu-latest
    environment: github-pages
    
    steps:
    - name: 1. checkout
      uses: actions/checkout@v2

    - name: 2. hexo build
      run: |
        ls -al
        mv themes/next/_config.yml.bak themes/next/_config.yml
        sed -i "s@<avatar_url>@${{ secrets.AVATAR_URL }}@" themes/next/_config.yml
        sed -i "s/<livere_uid>/${{ secrets.LIVERE_UID }}/" themes/next/_config.yml
        sed -i "s/<gitalk_client_id>/${{ secrets.GITALK_CLIENT_ID }}/" themes/next/_config.yml
        sed -i "s/<gitalk_client_secret>/${{ secrets.GITALK_CLIENT_SECRET }}/" themes/next/_config.yml
        grep -rF '../assets/images' source/_posts/ | awk -F':' '{print $1}' |sort |uniq |xargs sed -i "s@\([\(\"\']\).*/assets/images@\1https://${{ secrets.OSS_DOMAIN }}/images/@"
        docker run --rm -v "$(pwd):/opt/docs" lzzeng/node-hexo-cli:alpine
        
    - name: 3. push to github pages
      env:
        GIT_DEPLOY_REPO: https://${{ secrets.TOKEN }}@github.com/lzzeng/lzzeng.github.io.git
        GIT_DEPLOY_DIR: public
        GIT_DEPLOY_BRANCH: master
        GIT_DEPLOY_USERNAME: lzzeng
      run: |
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "${GIT_DEPLOY_USERNAME}"
        cd "${GIT_DEPLOY_DIR}"
        sudo mv assets/music/index.html.2 assets/music/index.html
        sudo git init
        sudo git add .
        sudo git commit -m "update github pages"
        sudo git push --force --quiet "${GIT_DEPLOY_REPO}" master:${GIT_DEPLOY_BRANCH}
